apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  annotations:
  name: letsencrypt-prod
  namespace: keycloak
spec:
  acme:
    email: me@example.com
    privateKeySecretRef:
      name: cert-manager-issuer-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
